/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_maimiao_live_jni_JNIAdapter */

#ifndef _Included_com_maimiao_live_jni_JNIAdapter
#define _Included_com_maimiao_live_jni_JNIAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maimiao_live_jni_JNIAdapter
 * Method:    getstringFromJNI
 * Signature: ()Ljava/lang/String;
 */
jstring Java_com_maimiao_live_jni_JNIAdapter_getstringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
